### ISSUE TITLE
localStorage 中的ac_time_value字段在哪？

### ISSUE THREAD

**Issue by HX-Wrdzgzs** [jingming295/bilibili-login#4]
不清楚localstronge在哪一块

**Comment by jingming295** [comment]
Local Storage在这里：
![image](https://github.com/jingming295/bilibili-login/assets/48265334/169fa6ce-0edf-42e2-ac32-91e6af5dd518)

中文(本地储存空间)：
![image](https://github.com/jingming295/bilibili-login/assets/48265334/a0a5bd20-5639-43d4-95d4-c3ab2196cd26)

**Comment by HX-Wrdzgzs** [comment]
OK，谢谢

**Comment by Maggieyml** [comment]
然而里面没有 ac_time_value字段？

**Comment by HX-Wrdzgzs** [comment]
E，在存储里面找，比较麻烦
