### ISSUE TITLE
在local并没有找到关于ac-time的字条，想问这被放到了哪里

### ISSUE THREAD

**Issue by HX-Wrdzgzs** [jingming295/bilibili-login#5]

**Comment by HX-Wrdzgzs** [comment]
![Screenshot_20240302_234358.jpg](https://github.com/jingming295/bilibili-login/assets/141598320/63112ecf-8966-4ace-ba59-18a05a1dc5bb)

**Comment by jingming295** [comment]
![7((XGUSIDIX{$ %GWSX_D$Q](https://github.com/jingming295/bilibili-login/assets/48265334/04b999d6-52fe-4201-96a0-b09b65460b3b)
在这个位置哦，如果找不到可能要重新登录下，或者重载网页

**Comment by HX-Wrdzgzs** [comment]
谢谢你的帮助，在运行插件时出现错误
错误日志![Screenshot_20240303_101205.jpg](https://github.com/jingming295/bilibili-login/assets/141598320/ade979b6-de32-4fb1-8439-67bca7e03c34)

![Screenshot_20240303_101158.jpg](https://github.com/jingming295/bilibili-login/assets/141598320/7f0ebf1b-3d95-4899-96e5-3519a818f3ec)

这是我在主页面获取的cookie
`buvid3=C2566C43-BBAB-CF0D-26B7-49CE57219CDD93697infoc; b_nut=1705568993; i-wanna-go-back=-1; b_ut=7; _uuid=3A513216-10545-11310-610D4-A6C7EC6F214F94246infoc; enable_web_push=DISABLE; buvid_fp=83ee3d936a662861d173e2d02b2a22d4; buvid4=29CBCED6-EAB6-49F9-07CD-ACD3BB66471295558-024011809-%2FswMhD3qtvw9JKoqAQbSaQ%3D%3D; header_theme_version=CLOSE; CURRENT_FNVAL=16; rpdid=|(JRuRYR)Ju|0J'u~|lYYmlum; home_feed_column=4; FEED_LIVE_VERSION=V_FAVOR_WATCH_LATER; b_lsid=161C84E2_18E01D70D36; bili_ticket=eyJhbGciOiJIUzI1NiIsImtpZCI6InMwMyIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDk2OTA2MjYsImlhdCI6MTcwOTQzMTM2NiwicGx0IjotMX0.WHM6EovAMbR_i1rGIDQOsF2MMFM8vAN7IrTPWHbHcTk; bili_ticket_expires=1709690566; SESSDATA=243bf3ea%2C1724983447%2Ca3ebe%2A32CjBhLvHfLP7zy706lvaTSzU1hO9fFMoNSGgmLi7VI1esobIJCskzAob1FAi_oe679cYSVnN4cEtKN0EtM2FEeGtVcDcxSFRqQTc2NUFqQ2xPeVFGZHd3QWdPVGRSRW5PRm9HNlE4TDBQNExUc1YzbU1tTFVQQUs3TjBPM3VlZGdMLXNQZGJ1dld3IIEC; bili_jct=9d0554c455c1a075403aeb723f301517; DedeUserID=1318034178; DedeUserID__ckMd5=960ed4cf6fcaacd2; sid=qkmj44ow; x-bili-gaia-vtoken=eec25d02271c4c1dad500ef029c40328; browser_resolution=150-1133`
我是在这边获取的
![Screenshot_20240303_101421.jpg](https://github.com/jingming295/bilibili-login/assets/141598320/e203dd5a-aaad-44bf-a2ee-68edf5401f8e)

可能是我想着随便找一个来获取cookie，是有什么要求吗

**Comment by jingming295** [comment]
要换个游览器登录b站获取，然后就是建议不要把这些cookie内容发出来，建议遮挡一部分。将这些cookie发出来有可能导致你的账号被盗取。

还有就是，sessdata，csrf和refresh token是一起配对的，也就是说你每次重新登录都需要把这三个内容重新获取并且重新输入，不存在上一次登录的refresh token和这一次的sessdata或者csrf一起用的情况

**Comment by jingming295** [comment]
你等我一下，我今天做个扫码登录的功能出来

**Comment by jingming295** [comment]
我弄了个扫码登陆，你试试

**Comment by HX-Wrdzgzs** [comment]
> 我弄了个扫码登陆，你试试

不好意思，我现在才看到此消息
感谢你的更新，不过我可能发现了问题
在手机端，即使使用电脑模式仍然会显示块状矩形，导致无法查看二维码，建议放在插件的主页。
需要多次登陆才可以使用（不清楚是地区原因还是插件原因）   
总之，十分感谢你的插件

**Comment by jingming295** [comment]
> > 我弄了个扫码登陆，你试试
> 
> 不好意思，我现在才看到此消息 感谢你的更新，不过我可能发现了问题 在手机端，即使使用电脑模式仍然会显示块状矩形，导致无法查看二维码，建议放在插件的主页。 需要多次登陆才可以使用（不清楚是地区原因还是插件原因） 总之，十分感谢你的插件

原来如此，手机端不是很好查看啊！那我得想个办法放在主页了

**Comment by HX-Wrdzgzs** [comment]
或许类似于onebot的扫二维码验证的形式来呈现B站的扫码登录，可能这是个好方法

**Comment by jingming295** [comment]
> 或许类似于onebot的扫二维码验证的形式来呈现B站的扫码登录，可能这是个好方法

好的，我会参考的
