### ISSUE TITLE
Q：bilibili -login需要和哪一个插件搭配使用

### ISSUE THREAD

**Issue by HX-Wrdzgzs** [jingming295/bilibili-login#6]
已扫码登录，但仍显示未登录
kbot有一个bilibili订阅的插件似乎无法搭配
如图![Screenshot_20240503_112021_com.microsoft.rdc.androidx.jpg](https://github.com/jingming295/bilibili-login/assets/141598320/ea2ab1ae-cd2e-4bc2-82b7-77d8ebc6fb36)

**Comment by jingming295** [comment]
主要是和[iirose-media-request](https://github.com/jingming295/iirose-media-request)还有[nazrin-video-bilibili](https://github.com/jingming295/nazrin-video-bilibili)搭配，还有没有其他插件有用这个当前置我就不知道了。有没有登录成功要看日志那边。
